### ISSUE TITLE
bug: [DESCRIPTION] SFT trainer does not use GPU

### ISSUE THREAD

**Issue by AvivSham** [janhq/ichigo#104]
## Problem
Thank you for this amazing repo, well done!
We followed your README and setup the env without any issues. Then we tried to train a model on NVIDIA A10G GPU with 24 GB VRAM memory, but we faced OOM error. We tried to switch the pretrained model to a smaller version i.e. `homebrewltd/mini-Ichigo-llama3.2-3B-s-instruct` and indeed the model was loaded to the GPU but when the training steps started there was no sign of GPU utilization (it remains 0% while the VRAM is used). We tried to play with the training config without success.

Can you please help with this?
Thank you!

**Comment by bachvudinh** [comment]
Thank you for your kind words. I wanted to clarify - did you try to use the Hugging Face SFT (Supervised Fine-Tuning) Trainer to train?

**Comment by bachvudinh** [comment]
Unfortunately, we no longer support the SFT trainer as of version 0.3. Instead, we now use Torchtune for training. Could you please try using Torchtune for your training needs?

**Comment by tikikun** [comment]
can you help updating the README inside hf codebase to make a warning about deprecation? @bachvudinh

**Comment by AvivSham** [comment]
I will give it a go, please leave this issue open ATM.

**Comment by AvivSham** [comment]
Ok so after deep dive running training using `torchtune` does not work at the moment and this is after we fixed several things along the way. Threre are some missing parts which should be included in the README:

1. There is a mismatch between the config file the user is directed to edit and the run command. https://github.com/homebrewltd/ichigo/blob/e380a7a956f13effd529b957cf29e6397ea9ee55/README.md?plain=1#L121-L129

2. In `recipes/configs/jan-llama3-1-s/8B_full.yaml` config file the model components should be changed to 4 shards of safetensors instead of model.bin (since this is the format of your models).

3. To instantiate llama's tokenizer one needs the `tokenizer.model`, this is not mentioned in the README, but my guess is that you are referring to this [llama artifact](https://huggingface.co/meta-llama/Meta-Llama-3-8B/tree/main/original).

4. We tried to fine-tune ichigo-0.4v using the `homebrewltd/mixed-instruction-speech-whispervq-v4` dataset, however still facing some issues.
We used the following configuration:
```
# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_s_tokenizer
  path: /home/ubuntu/code/model_zoo/ichigo-llama3.1-s-instruct-v0.4/tokenizer.model

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: homebrewltd/mixed-instruction-speech-whispervq-v4
  conversation_style: openai
  max_seq_len: 2048
  split: train
  train_on_input: True

seed: 42
shuffle: True
# Model Arguments
model:
  _component_: torchtune.models.llama3_1.llama3_1_s_8b
  # path: model_zoo/Llama3.1_s_8b_init
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointerSaveSteps
  checkpoint_dir: /home/ubuntu/code/model_zoo/ichigo-llama3.1-s-instruct-v0.4
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors,
  ]
  recipe_checkpoint: null
  output_dir: /home/ubuntu/code/model_zoo
  model_type: LLAMA3
resume_from_checkpoint: False
save_every_n_steps: 500
max_checkpoints: 3
# Fine-tuning arguments
batch_size: 2
epochs: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 4
compile: False
# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW #change this to use adam_mini: torchtune.modules.optimizer.Adam_mini
  weight_decay: 0.01
  lr: 2e-4
  fused: True
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 200

loss:
  _component_: torch.nn.CrossEntropyLoss

fsdp:
  cpu_offload: False

# Training env
device: cuda
dtype: bf16

# Memory management
enable_activation_checkpointing: True
memory_efficient_fsdp_wrap: True
ac_mode: 'selective'


# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: ../model_zoo/Llama3-instruct-log/
log_every_n_steps: 1
log_peak_memory_stats: False
```

And received the following error:
```
INFO:torchtune.utils._logging:Optimizer and loss are initialized.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/recipes/full_finetune_fsdp2.py", line 731, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/torchtune/config/_parse.py", line 99, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/recipes/full_finetune_fsdp2.py", line 725, in recipe_main
[rank0]:     recipe.setup(cfg=cfg)
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/recipes/full_finetune_fsdp2.py", line 256, in setup
[rank0]:     self._sampler, self._dataloader = self._setup_data(
[rank0]:                                       ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/recipes/full_finetune_fsdp2.py", line 446, in _setup_data
[rank0]:     ds = config.instantiate(cfg_dataset, tokenizer=self._tokenizer)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/torchtune/config/_instantiate.py", line 112, in instantiate
[rank0]:     return _instantiate_node(OmegaConf.to_object(config), *args)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/torchtune/config/_instantiate.py", line 33, in _instantiate_node
[rank0]:     return _create_component(_component_, args, kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/code/ichigo/torchtune/torchtune/config/_instantiate.py", line 22, in _create_component
[rank0]:     return _component_(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: TypeError: chat_dataset() missing 1 required keyword-only argument: 'conversation_column'
```

My guess is that you need to change the `conversation` column in your datasets to `conversation_column`.

@tikikun @bachvudinh  please advise.
